import React, { useState, useRef, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';

export const Navbar: React.FC = () => {
  const { user, logout, isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (e: MouseEvent) => { if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) setDropdownOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  const name = user?.name || user?.email?.split('@')[0] || 'User';
  const initials = name.split(' ').map(x => x[0]).join('').slice(0, 2).toUpperCase();
  return <nav className="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="container-custom flex h-[72px] items-center justify-between"><Link to="/" className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#073b63] text-lg font-bold text-white">S</span><span><b className="block text-base tracking-tight text-[#082f50]">SkillBridge</b><small className="block text-[9px] font-semibold uppercase tracking-[.12em] text-[#0d7c8a]">SIH26044</small></span></Link><div className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a href="#ecosystem" className="hover:text-[#0d7c8a]">How it works</a><a href="#ecosystem" className="hover:text-[#0d7c8a]">For institutions</a><a href="#ecosystem" className="hover:text-[#0d7c8a]">For industry</a></div><div className="flex items-center gap-3">{isAuthenticated ? <div className="relative" ref={dropdownRef}><button onClick={() => setDropdownOpen(!dropdownOpen)} className="flex items-center gap-2 rounded-lg p-1.5 hover:bg-slate-50"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#e0f2f1] text-xs font-bold text-[#087a73]">{initials}</span><span className="hidden text-sm font-semibold text-slate-700 sm:block">{name}</span><span className="text-slate-400">⌄</span></button>{dropdownOpen && <div className="absolute right-0 mt-2 w-48 rounded-xl border border-slate-200 bg-white py-1 shadow-xl"><Link onClick={() => setDropdownOpen(false)} to={`/${user?.role}/dashboard`} className="block px-4 py-2 text-sm text-slate-700 hover:bg-slate-50">Dashboard</Link><button onClick={() => { logout(); navigate('/'); }} className="block w-full px-4 py-2 text-left text-sm text-red-600 hover:bg-red-50">Log out</button></div>}</div> : <><Link to="/login" className="hidden text-sm font-semibold text-slate-600 hover:text-[#0d7c8a] sm:block">Log in</Link><Link to="/register" className="rounded-lg bg-[#073b63] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#052f50]">Get started</Link></>}</div></div></nav>;
};
